In [6]:
import numpy as np
my_lst = [1,2,3,4]
arr = np.array(my_lst)
print(arr)

[1 2 3 4]


In [8]:
my_lst1 = [1,2,3,4]
my_lst2 = [4,5,6,7]
my_lst3 = [7,8,9,10]
arr=np.array([my_lst1, my_lst2, my_lst3])
print(arr)


[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [9]:
arr.shape

(3, 4)

In [10]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [ 6,  7,  7],
       [ 8,  9, 10]])

In [11]:
arr[2]

array([ 7,  8,  9, 10])

In [12]:
arr[0:,:]

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [13]:
arr[1:,2:]

array([[ 6,  7],
       [ 9, 10]])

In [14]:
newArr = np.arange(1,10, step = 2)
print(newArr)

[1 3 5 7 9]


In [16]:
arr1 = newArr.copy()
print(arr1)

[1 3 5 7 9]


In [17]:
val= 200
arr[arr<val]

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10])

In [18]:
arr*2

array([[ 2,  4,  6,  8],
       [ 8, 10, 12, 14],
       [14, 16, 18, 20]])

In [19]:
np.random.rand(3,3)

array([[0.85259413, 0.30491346, 0.25326087],
       [0.01996675, 0.73819604, 0.56050441],
       [0.40323333, 0.04699088, 0.69004384]])

In [20]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
np.random.randint(0,100,8).reshape(2,4)

array([[74, 89, 95, 68],
       [55, 28, 48, 72]], dtype=int32)